//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanky
    {
        public int ID { get; set; }
        public string Nazev { get; set; }
        public System.DateTime Datum_Vytvoreni { get; set; }
        public string Text { get; set; }
    }
}
